server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: aggregation
#     active: dev
  data:
    redis:
      host: 120.46.212.99
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 120.46.212.99:8848