server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
#    active: aggregation
     active: dev
  data:
    redis:
      host: 1.92.99.22
      port: 6379
      password: JN58fote
  cloud:
    nacos:
      discovery:
        server-addr: 43.139.204.197:8848
