server:
  port: 8001

spring:
  application:
    name: short-link-project
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 43.139.204.197
      port: 6379
      password: 123456
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 43.139.204.197:8848

rocketmq:
  name-server: 43.139.204.197:9876
  producer:
    group: short-link_project-service_stats-save_pg
    topic: short-link_project-service_topic
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 5fcb9ed025328b920fc938167b3408ba
    goto-domain:
      white-list:
        enable: true
        names: '知乎,掘金,博客园'
        details:
          - zhihu.com
          - juejin.cn
          - cnblogs.com