server:
  port: 8001
spring:
  datasource:
    username: link
    password: qaz//0@@
    url: jdbc:mysql://bj-cynosdbmysql-grp-bbar73yo.sql.tencentcdb.com:22983/link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: 43.139.204.197
      port: 6379
      password: 123456